[theme]
primaryColor = "#0033A0"  # Azul profundo
backgroundColor = "#E0E7FF"  # Fondo azul claro
secondaryBackgroundColor = "#FFFFFF"  # Fondo de la barra lateral en blanco
textColor = "#000000"  # Texto en negro
font = "serif"
